# Generated by Django 2.2.12 on 2025-04-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
